### ISSUE TITLE
Feature: be more configurable

### ISSUE THREAD

**Issue by shigma** [H4M5TER/milestone-backlog#4]
- **header:** `string`, default to `# Backlog`

**Comment by shigma** [comment]
https://github.com/H4M5TER/milestone-backlog/blob/8c87d612cc609044f3a5905e16d29c31e2e569b7/index.ts#L29

Should this be related to `label`?

**Comment by H4M5TER** [comment]
`labels` is correct.
Check <https://docs.github.com/en/rest/issues/issues#list-repository-issues>

**Comment by shigma** [comment]
I mean you have a config called `label` and set to `plan`, however now you hardcoded `plan` here.

**Comment by H4M5TER** [comment]
you are right.
It's a mistake since `label` is only used to bypass.
